server:
  # To avoid colliding with other apps in port 8080
  port: 8081

# App metadata
info:
  app:
    name: Notification Microservice
    description: '@project.description@'
    version: 1.0.0
  company:
    name: Pontificia Universidad Javeriana - Grupo 4
    contact:
      email: support@mycompany.com
      phone: +1234567890
  build:
    time: ${BUILD_TIME:2024-08-21T12:30:00Z}

#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://kevinevelasco:kevinevelasco@msc-cluster.gh4kp.mongodb.net/?retryWrites=true&w=majority&appName=msc-cluster
#      database: notifications